stages:
  - test
  - build

cache:
  paths:
    - node_modules/

## Environments
.node_env: &node_env
  image: node:14.18
  tags:
    - linux
    - docker

## Jobs
code-check:
  <<: *node_env
  stage: test
  script:
    - npm run lint

test:
  <<: *node_env
  stage: test
  script:
    - npm run test:cov

build:
  <<: *node_env
  stage: build
  script:
    - npm run build

